# Generated by Django 5.2.3 on 2025-06-23 05:19

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readinglist_readinglistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Lower('authors'), models.F('owner'), name='unique_case_insensitive_book_per_user'),
        ),
    ]
